### ISSUE TITLE
Rune pouch not able to be excluded

### ISSUE THREAD

**Issue by korboybeats** [wikiworm/InventoryValue#18]
I typed 'Rune pouch' in the ignore items list, but the value tracker still tracks all my runes in it.

![image](https://user-images.githubusercontent.com/80824905/221393132-88e23b2f-8fd3-4ebc-a2d3-0d0d308d225e.png) ![image](https://user-images.githubusercontent.com/80824905/221393131-0d02680c-550c-4806-899b-9123e47ea85e.png)

**Comment by wikiworm** [comment]
I was able to repro this. I'll investigate and post a fix.

**Comment by wikiworm** [comment]
Thank you for bringing this to my attention. This is now fixed. I'll post a merge request to the plugin hub ASAP.

**Comment by korboybeats** [comment]
> Thank you for bringing this to my attention. This is now fixed. I'll post a merge request to the plugin hub ASAP.

Hmm, it's still calculating the runes in the rune pouch

**Comment by wikiworm** [comment]
> Hmm, it's still calculating the runes in the rune pouch

[RuneLite has not merged the new PR (with the fix) yet](https://github.com/runelite/plugin-hub/pull/3976). I think there were a little over 30 before the InventoryValue one was submit. Last time it took about a week for a new build to be made public. Sorry for the delay.
